version: '2'
services:
   db:
    image: postgres:13  
    restart: always
    environment:
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: library
    ports:
      - "5432:5432"  
   app:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ".:/noteapp"
    ports:
      - "3001:3001"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: noteapp
      DB_PASSWORD: password
      DB_HOST: db